name: CI

on:
  push: ~

jobs:
  tests:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.1'
      - name: Install composer
        run: composer install --no-interaction --no-progress --no-scripts --prefer-dist
      - name: Copy .env
        run: cp .env.example .env
      - name: Start services
        run: vendor/bin/sail up --wait
      - name: Run static analyze
        run: vendor/bin/sail bin phpcs
      - name: Run migrations
        run: vendor/bin/sail artisan migrate:fresh
      - name: Seed database
        run: vendor/bin/sail artisan db:seed
      - name: Run phpunit
        run: vendor/bin/sail artisan test
